### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by yx-chan131** [JaihyunKoh/BNUDC#1]
In the paper it was mentioned that the model was trained on patches from full resolution images, but I didn't see any cropping operation in udc_dataset.py. Are you using random cropping on the fly? I would like to know the cropping size too.

I used the provided pretrained POLED model to test on POLED test set, however the result is far off from the paper's.

**Comment by JaihyunKoh** [comment]
Thank you for your note. To train, we used a full-sized image, which means no crop operation was used in training, but, if you have CUDA out of memory issues, you can use any cropping operation as you mentioned.

For test results in the POLED dataset, you should use the pre-processed input images which we provide. If you downloaded the pre-processed images from the dataset link, please double-check the input image path in base_options.py

**Comment by JaihyunKoh** [comment]
> 

Thank you for your note. To train, we used a full-sized image, which means no crop operation was used in training, but, if you have CUDA out of memory issues, you can use any cropping operation as you mentioned.

For test results in the POLED dataset, you should use the pre-processed input images which we provide. If you downloaded the pre-processed images from the dataset link, please double-check the input image path in base_options.py

**Comment by JaihyunKoh** [comment]
> In the paper it was mentioned that the model was trained on patches from full resolution images, but I didn't see any cropping operation in udc_dataset.py. Are you using random cropping on the fly? I would like to know the cropping size too.
> 
> I used the provided pretrained POLED model to test on POLED test set, however the result is far off from the paper's.

Thank you for your note. To train, we used a full-sized image, which means no crop operation was used in training, but, if you have CUDA out of memory issues, you can use any cropping operation as you mentioned.

For test results in the POLED dataset, you should use the pre-processed input images which we provide. If you downloaded the pre-processed images from the dataset link, please double-check the input image path in base_options.py

**Comment by yx-chan131** [comment]
Thanks for your reply. It is all clear now. 

Regarding the SYNTH dataset, how do you get the GT and LQ paired dataset? There's no keywords e.g. blur, LQ in the datasets.
