### ISSUE TITLE
SYNTH dataset GT and LQ pair

### ISSUE THREAD

**Issue by yx-chan131** [JaihyunKoh/BNUDC#2]
Hi, I downloaded the SYNTH dataset and I found out that there is no keywords e.g. blur sharp, LQ. How do you get the input and ground-truth pair?

**Comment by JaihyunKoh** [comment]
> Hi, I downloaded the SYNTH dataset and I found out that there is no keywords e.g. blur sharp, LQ. How do you get the input and ground-truth pair?

Thank you for your note again.
As described in image_handler.py, images in folder /sharp, /GT, or /HQ are regarded as ground truth images, while /blur, /input, or /LQ assigned to corrupted input. Please note that you should change 'LQ' to 'LQ_pre' in using pre-processed images for POLED dataset. I regret this inconvenience.

os.path.basename(root) == 'sharp' or os.path.basename(root) == 'GT' or os.path.basename(root) == 'HQ'
os.path.basename(root) == 'blur' or os.path.basename(root) == 'input' or os.path.basename(root) == 'LQ'

**Comment by yx-chan131** [comment]
Hi, thanks for your reply but you misunderstand my question. In SYNTH dataset the LQ image is generated by convoluting GT image with PSF kernel. From SYNTH github I found that there are 10 PSF positions. I would like to know are you using images generated from all 10 PSFs to train model or you just choose one subset.

**Comment by JaihyunKoh** [comment]
> Hi, thanks for your reply but you misunderstand my question. In SYNTH dataset the LQ image is generated by convoluting GT image with PSF kernel. From SYNTH github I found that there are 10 PSF positions. I would like to know are you using images generated from all 10 PSFs to train model or you just choose one subset.

I followed the data generation process in (https://github.com/jnjaby/DISCNet), which means I used 2,016 * 10 PSFs UDC images for training and 360 * 10 for testing.

**Comment by yx-chan131** [comment]
Thank you! May I know how many epochs (opt.niter) and batch size you set for training on SYNTH dataset?

**Comment by JaihyunKoh** [comment]
We set batch_size 4, and train_epochs 40. Thank you!!!

**Comment by yx-chan131** [comment]
Hi I got question again... What are the loss weights you used when training on SYNTH? In paper it was only mentioned that L1 loss and Perceptual Loss are being applied.

**Comment by JaihyunKoh** [comment]
A weight 0.01 is applied to the perceptual loss. It may be same as DISCnet.
